[package]
name = "sharad_ratatui"
version = "0.1.14"
edition = "2021"

[dependencies]
async-openai = "0.23.3"
chrono = "0.4.38"
cleanup = "0.1.1"
copypasta = "0.10.1"
crossterm = "0.27.0"
ctrlc = "3.4.4"
hyphenation = "0.8.4"
libc = "0.2.155"
rand = "0.8.5"
ratatui = "0.27.0"
reqwest = { version = "0.12.5", features = ["json"] }
ropey = "1.6.1"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.118"
textwrap = { version = "0.16.1", features = ["hyphenation"] }
thiserror = "1.0.61"
tokio = { version = "1.38.0", features = ["full"] }
tui-input = "0.9.0"
unicode-segmentation = "1.11.0"
unicode-width = "0.1.13"
whatlang = "0.16.4"
