[package]
name = "sharad_ratatui"
version = "0.1.17"
edition = "2021"

[dependencies]
async-openai = "0.24.0"
chrono = "0.4.38"
cleanup = "0.1.1"
copypasta = "0.10.1"
cpal = "0.15.3"
crossterm = "0.28.1"
ctrlc = "3.4.5"
futures = "0.3.30"
hound = "3.5.1"
hyphenation = "0.8.4"
lame = "0.1.3"
libc = "0.2.158"
rand = "0.8.5"
ratatui = "0.28.1"
rayon = "1.10.0"
reqwest = { version = "0.12.7", features = ["json"] }
rodio = "0.19.0"
ropey = "1.6.1"
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"
textwrap = { version = "0.16.1", features = ["hyphenation"] }
thiserror = "1.0.63"
tokio = { version = "1.40.0", features = ["full"] }
tui-input = "0.10.1"
unicode-segmentation = "1.11.0"
unicode-width = "0.1.13"
uuid = { version = "1.10.0", features = ["v4"] }
