[package]
name = "sharad_ratatui"
version = "0.0.1"
edition = "2021"

[dependencies]
async-openai = "0.23.3"
chrono = "0.4.38"
cleanup = "0.1.1"
crossterm = "0.27.0"
ctrlc = "3.4.4"
libc = "0.2.155"
rand = "0.8.5"
ratatui = "0.27.0"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.118"
textwrap = "0.16.1"
tokio = { version = "1.38.0", features = ["full"] }
